# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  python:
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"

  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: python
    commit-message:
      prefix: "build"

  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: python
    commit-message:
      prefix: "build"
